[package]
name = "ttyrec-bin"
version = "0.1.2"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2021"

description = "record and play back ttyrec files"
repository = "https://git.tozt.net/ttyrec-bin"
readme = "README.md"
keywords = ["ttyrec"]
categories = ["command-line-utilities"]
license = "MIT"

[dependencies]
anyhow = "1.0.51"
async-std = { version = "1.10.0", features = ["unstable"] }
libc = "0.2.112"
paw = "1.0.0"
pty-process = { version = "0.2.0", features = ["backend-async-std"] }
signal-hook = "0.3.12"
signal-hook-async-std = "0.2.1"
structopt = { version = "0.3.25", features = ["paw", "wrap_help"] }
terminal_size = "0.1.17"
textmode = { version = "0.3.0", features = ["async"] }
ttyrec = { version = "0.3.3", features = ["async"] }
vt100 = "0.15.0"
