[package]
name = "ttyrec-bin"
version = "0.1.0"
edition = "2021"

license = "MIT"

[dependencies]
anyhow = "1.0.51"
async-std = { version = "1.10.0", features = ["unstable"] }
libc = "0.2.109"
paw = "1.0.0"
pty-process = { version = "0.1.1", features = ["backend-async-std"] }
signal-hook = "0.3.10"
signal-hook-async-std = "0.2.1"
structopt = { version = "0.3.25", features = ["paw", "wrap_help"] }
terminal_size = "0.1.17"
textmode = { version = "0.2.1", features = ["async"] }
ttyrec = { version = "0.3.2", features = ["async"] }
vt100 = "0.13.2"
